version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_TYPE=python
      - NEXT_PUBLIC_PYTHON_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  # Python FastAPI Backend
  backend:
    build:
      context: ./Pythonagents/fastapi-mcp-agent
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./Pythonagents/fastapi-mcp-agent:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Socket.IO Server (if still needed)
  socket-server:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - ./socket-server:/app
      - /app/node_modules
    command: npm run dev